variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprcommondataregistry'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprcommondataregistry'
  serviceName: 'prdrwdwebwa1415'
  kvName: PRDRWDINFKV1401
  sqlDBserver: prdrwddbssq1401.database.windows.net
  sqlDB: 'prd1_accounts'